<footer>
	<div id="SOLfooterLinks" class="clear">
		<ul class="lp_linker">
			<li>
				<ul class="logo">
					<li>
						<a href="http://www.sol.no">
							<span class="img">Scandinavia Online AS</span>
						</a>
					</li>
					<li class="spacer"></li>
				</ul>
			</li>
			<li>
				<ul class="links">
					<li class="strong first">
						<a class="int" href="http://www.sol.no/infoweb/omsol">Om SOL</a>
					</li>
					<li class="strong">
						<a class="int" href="http://www.sol.no/infoweb/node/70">Kontakt oss</a>
					</li>
					<li class="strong last">
						<a class="int" href="http://www.sol.no/infoweb/annonsere">Annonsere?</a>
					</li>
					<li class="strong last">
						<a class="int" href="http://www.sol.no/nyheter/2013_07_02_19144_personvern-og-cookies.html">Om cookies</a>
					</li>
				</ul>
			</li>
			<li>
				<ul class="about">
					<li class="first">Stenersgata 2, 0184 Oslo</li>
					<li class="last">Org.nr: 988 875 740</li>
				</ul>
			</li>
			<li>
				<ul class="bosses">
					<li class="first">
						<span>Ansvarlig redaktør:</span>
						<a href="mailto:FJERNDETTEstephan.granhaug@sol.no">Stephan Granhaug</a>
					</li>
					<li>
						<span>Redaktør:</span>
						<a href="mailto:FJERNDETTEper.tandberg@sol.no">Per Tandberg</a>
					</li>
					<li class="last">
						<span>Vaktsjef nå: </span>
						<a href="mailto:FJERNDETTEtrond.alsvik@sol.no">Trond Alsvik</a>
					</li>
				</ul>
			</li>
		</ul>
		<div style="clear:both"></div>
	</div>
</footer>