<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
    <link href='/css/front-56.css' rel='stylesheet' type='text/css'>
    <link href='/css/responsive.css' rel='stylesheet' type='text/css'>
    <title>Title Goes Here</title>
</head>



<body>
    <?php include('header.phtml'); ?>
    <div class="maincontainer">
      <?php echo $this->content; ?>
    </div>
    <?php include('footer.phtml'); ?>
    <script type="text/javascript" async="" src="/js/vendor/headroom/headroom.js"></script>


    <script type="text/javascript">
    	var myElement = document.querySelector("header");
    	var headroom  = new Headroom(myElement, {
      "tolerance": 5,
      "offset": 105,
      "classes": {
        "initial": "animated",
        "pinned": "slideDown",
        "unpinned": "slideUp"
      }
    });
    	headroom.init(); 
    </script>
</body>
</html>